language: node_js
sudo: false
node_js:
    - '13.6.0'

cache:
    directories:
        - node_modules

install:
    - yarn install --frozen-lockfile --non-interactive

script:
    - yarn lint --cache
    - yarn build
    - yarn test:ci

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && chmod +x publish.sh && ./publish.sh
